config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :users do
    resource :relationships, only: [:create, :destroy]
  end
  resources :items do
    resources :orders, only: [:index, :create]
    resource :likes,  only: [:create, :destroy]
    resources :users do
      resource :relationships, only: [:create, :destroy]
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
before_action :like_item

  def create
    like = current_user.likes.build(item_id: params[:item_id])
    like.save
    render partial: 'likes/like', locals: { item: @item }
  end

  def destroy
    like = Like.find_by(item_id: params[:item_id], user_id: current_user.id)
    like.destroy
    render partial: 'likes/like', locals: { item: @item }
  end


  def like_item
    @item = Item.find(params[:item_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<%= turbo_frame_tag dom_id(@item, :like) do %>
  <% if user_signed_in? %>
    <% if @item.liked_by?(current_user)%>
      <%= link_to item_likes_path(@item.id), data: { turbo_method: :delete } do %>
        <%= image_tag "heart-pink.png", class: "favorite-heart-icon", width: "20", height: "20" %>
        <span style="color:rgb(249, 75, 0)">いいね！<%= @item.likes.count %></span>
      <% end %>
    <% else %>
      <%= link_to item_likes_path(@item.id), data: { turbo_method: :post } do %>
        <%= image_tag "heart-black.png", class: "favorite-heart-icon", width: "20", height: "20" %>
        <span style="color:rgb(249, 75, 0)">いいね！<%= @item.likes.count %></span>
      <% end %>
    <% end %>
  <% else %>
    <%= image_tag "heart-black.png", class: "favorite-heart-icon", width: "20", height: "20" %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
document.getElementById('like-btn<%= @item.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {item: @item}) %>"

app/views/likes/destroy.js.erb
document.getElementById('like-btn<%= @item.id %>').innerHTML = "<%= j(render partial: 'likes/like', locals: {item: @item}) %>"